version: '3.8'

services:
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:arya19032004A*@postgres:5432/protextifyv2?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=YOUR_RANDOM_JWT_SECRET
      - JWT_EXPIRATION_TIME=3600s
    depends_on:
      - postgres
      - redis

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - uploads:/usr/src/app/uploads
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: arya19032004A*
      POSTGRES_DB: protextifyv2
    # Untuk keamanan, jangan expose port ke publik
    # ports:
    #   - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
  # Untuk keamanan, jangan expose port ke publik
  # ports:
  #   - "6379:6379"

  frontend:
    build:
      context: ../protextify-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - api

volumes:
  pgdata:
  uploads: