services:
  # Service untuk aplikasi NestJS
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development # Target stage development untuk live-reloading
    container_name: protextify_app
    ports:
      - '3000:3000' # Mapping port dari host ke container
      - '5555:5555' # Tambahkan baris ini
    volumes:
      - .:/usr/src/app # Sinkronisasi source code lokal ke container
      - /usr/src/app/node_modules # Mencegah volume menimpa node_modules di dalam container
    env_file:
      - .env # Menggunakan environment variables dari file .env
    command: npm run start:dev # Menjalankan dalam mode development
    depends_on:
      - postgres
      - redis
    networks:
      - protextify-net

  # Service untuk database PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: protextify_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data # Volume untuk persistensi data
    networks:
      - protextify-net

  # Service untuk Redis (untuk Queue & Caching)
  redis:
    image: redis:7-alpine
    container_name: protextify_redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - protextify-net

# Mendefinisikan network yang akan digunakan
networks:
  protextify-net:
    driver: bridge

# Mendefinisikan volume untuk persistensi data
volumes:
  postgres-data:
  redis-data:
